import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'demo — drift a city right now',
  description: 'Pick a city, tell us your vibe, and get a personalized walking route generated by AI.',
}
export default function DemoLayout({ children }: { children: React.ReactNode }) {
  return children
}
