'use client'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { FadeIn } from '@/components/FadeIn'

const LAST_UPDATED = 'May 2026'

const SECTIONS = [
  {
    title: 'acceptance of terms',
    body: [
      'By accessing or using driftd (driftd.world), you agree to these terms of service. If you don\'t agree, don\'t use the service.',
      'We may update these terms from time to time. Continued use of driftd after changes are posted means you accept the revised terms.',
    ],
  },
  {
    title: 'what driftd is',
    body: [
      'driftd is an AI-powered city exploration platform that generates personalized walking routes based on user preferences. It is currently in beta and offered free of charge to individual users.',
      'Routes are generated by AI and are intended for inspiration and exploration. They are not professional guides, safety assessments, or official tourism recommendations.',
    ],
  },
  {
    title: 'use of the service',
    body: [
      'You may use driftd for personal, non-commercial exploration. You may not use driftd to build competing products, scrape route data, or resell generated content.',
      'You are responsible for your own safety while following any driftd route. Always be aware of your surroundings, respect local laws, and use good judgment.',
      'We reserve the right to suspend or restrict access to driftd for any reason, including misuse or abuse of the service.',
    ],
  },
  {
    title: 'AI-generated content',
    body: [
      'Routes, stop descriptions, and narratives are generated by AI. They may contain inaccuracies, outdated information, or suggestions that are no longer applicable. Verify opening hours, addresses, and access before visiting any location.',
      'driftd makes no warranties about the accuracy, completeness, or fitness for purpose of any AI-generated content.',
    ],
  },
  {
    title: 'intellectual property',
    body: [
      'The driftd name, logo, design, and software are owned by driftd and protected by intellectual property law.',
      'Routes generated for you are yours to use personally. We retain the right to use anonymized, aggregated route data to improve the service.',
    ],
  },
  {
    title: 'limitation of liability',
    body: [
      'driftd is provided "as is" without warranties of any kind. We are not liable for any damages arising from your use of the service, including but not limited to personal injury, property damage, or data loss.',
      'To the maximum extent permitted by law, our total liability to you for any claim arising from use of driftd shall not exceed €100.',
    ],
  },
  {
    title: 'governing law',
    body: [
      'These terms are governed by the laws of Poland. Any disputes shall be resolved in the courts of Warsaw, Poland.',
    ],
  },
  {
    title: 'contact',
    body: [
      'Questions about these terms? Email hello@driftd.world.',
    ],
  },
]

export default function TermsPage() {
  return (
    <main>
      <Navbar />

      {/* Hero */}
      <section className="relative min-h-[40vh] flex items-end pb-16 md:pb-20 overflow-hidden noise-overlay pt-32">
        <div className="absolute inset-0 bg-[#070707]" />
        <div className="blob absolute opacity-10 pointer-events-none" style={{ width: 400, height: 400, top: '-10%', right: '-5%', background: 'radial-gradient(circle, #f59e0b 0%, transparent 70%)', filter: 'blur(100px)' }} />
        <div className="relative z-10 max-w-3xl mx-auto px-6 md:px-10 w-full">
          <FadeIn>
            <span className="text-[11px] tracking-[0.2em] uppercase text-amber-400/70 font-medium block mb-5">legal</span>
            <div className="divider mb-6" />
            <h1 className="font-display font-black text-warm-white leading-[0.92] tracking-tight" style={{ fontSize: 'clamp(2.4rem, 6vw, 4.5rem)' }}>
              terms of<br />
              <span className="italic gradient-text">service</span>
            </h1>
            <p className="text-warm-gray-400 text-sm mt-5">last updated: {LAST_UPDATED}</p>
          </FadeIn>
        </div>
      </section>

      {/* Body */}
      <section className="bg-[#080808] py-16 md:py-20">
        <div className="max-w-3xl mx-auto px-6 md:px-10">
          <FadeIn className="mb-12">
            <p className="text-warm-gray-200 text-lg leading-relaxed" style={{ fontWeight: 300 }}>
              these terms govern your use of driftd. we've tried to write them clearly — no legalese where we could avoid it.
            </p>
          </FadeIn>

          <div className="flex flex-col gap-12">
            {SECTIONS.map((s, i) => (
              <FadeIn key={s.title} delay={i * 40}>
                <div className="border-l-2 border-amber-400/15 pl-6">
                  <h2 className="text-base font-semibold text-warm-white mb-4 tracking-wide">{s.title}</h2>
                  <div className="flex flex-col gap-3">
                    {s.body.map((para, j) => (
                      <p key={j} className="text-warm-gray-300 text-sm leading-relaxed" style={{ fontWeight: 300 }}>
                        {para}
                      </p>
                    ))}
                  </div>
                </div>
              </FadeIn>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </main>
  )
}
